server:
  port: 8082

spring:
  application:
    name: LoginService

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/weblearningproject
    username: root
    password: Aa147258..

  cloud:
    nacos:
      server-addr: localhost:8848